[package]
name = "g"
version = "0.1.1"
edition = "2024"
authors = ["Thibaut Vuillemin <thibaut.vuillemin@icloud.com>"]
description = "A Git wrapper"
license = "MIT"
repository = "https://github.com/tvuillemin/g"

[dependencies]

[[bin]]
name = "g"
path = "src/main.rs"
